---
name: Gataria CI/CD Prod
on:
  push:
    branches:
      - main

jobs:
  build-prod:
    name: Build prod
    if: contains (github.ref, 'main')
    runs-on: self-hosted
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Docker login
      run: docker login -u ${{ vars.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASS }}
    - name: Docker build
      run: docker build -t fernandindtjr/gataria-frontend:prod$GITHUB_SHA . --build-arg REACT_APP_STAGE=prod
    - name: docker push
      run: docker push fernandindtjr/gataria-frontend:prod$GITHUB_SHA
  test-prod:
    name: Test prod
    if: contains (github.ref, 'main')
    runs-on: self-hosted
    needs: build-prod
    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm ci
    - name: Run test
      run: npm test
      
  deploy-prod:
    name: Deploy prod
    if: contains (github.ref, 'main')
    runs-on: self-hosted
    needs: test-prod
    container: 
      image: fernandindtjr/gataria-deploy:1.0
      credentials: 
        username: ${{ vars.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASS }}
    steps:
    - name: Add ChartMuseum Repo
      run: helm repo add gataria-charts http://chartmuseum:8080   
    - name: helm update repo
      run: helm repo update
    - name: Deploy prod
      run: helm upgrade gataria-frontend gataria-charts/gataria-frontend -n prod --set "image.tag=prod$GITHUB_SHA" --set "ingress.hosts[0].hosts=gataria.example" --set "ingress.hosts[0].paths[0].path=/*" --set "ingress.hosts[0].paths[0].pathType=Prefix" --set "autoscaling.enabled=true" || helm install gataria-frontend gataria-charts/gataria-frontend -n prod --set "image.tag=prod$GITHUB_SHA" --set "ingress.hosts[0].hosts=gataria.example" --set "ingress.hosts[0].paths[0].path=/" --set "ingress.hosts[0].paths[0].pathType=Prefix" --set "autoscaling.enabled=true"